# This workflow will install Python dependencies, run tests and lint with a variety of Python versions
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Python package

on: [push, workflow_dispatch]

jobs:
  py-build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Set up Python 3.8
        uses: actions/setup-python@v3
        with:
          python-version: 3.8

      - name: Install dependencies
        run: |
          python3 --version
          python3 -m pip install --upgrade pip
          python3 -m pip install --upgrade nox

      - name: Test with nox
        run: |
          git config --global user.name "Austin Page"
          git config --global user.email "jaustinpage@gmail.com" 
          nox --session check_format test lint "docs(test)"

      - name: Build Python Wheels
        run: |
          nox --session build "docs(build)" "docs(pdf)"

      - name: Upload built python
        uses: actions/upload-artifact@v2
        with:
          name: app-artifacts
          path: |
            dist/silver_spork*.whl
            dist/silver-spork*.tar.gz
  
  py-platform-check:
    runs-on: ${{matrix.os}}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        python-version: ["3.8", "3.10"]

    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: main branch hash
        id: main-sha
        run: |
          echo "::set-output name=SHA::$(git log -n 1 --pretty=format:%H refs/remotes/origin/main)"
      - name: Get specific changed files
        id: python-app-files
        uses: tj-actions/changed-files@v16
        with:
          base_sha: ${{ steps.main-sha.outputs.SHA }}
          files: |
            src/**/*.py
            tests/*.py
            tests/**/*.py

      - name: Set up Python ${{ matrix.python-version }}
        if: steps.python-app-files.outputs.any_changed == 'true'
        uses: actions/setup-python@v3
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        if: steps.python-app-files.outputs.any_changed == 'true'
        run: |
          python3 --version
          python3 -m pip install --upgrade pip
          python3 -m pip install --upgrade nox
      - name: Test with nox
        if: steps.python-app-files.outputs.any_changed == 'true'
        run: |
          nox --session test_py-{{matrix.python-version}}
